name: CI
on: 
  push:
    branches: 
      - main
jobs:
  test:
    name: Code-coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: action/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
      - name: Install requirements
        run:  npm install
      - name: Run tests
        run: npx jest --coverage
      - name: Calculate Code Coverage
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN}}
