name: CI
on: 
  push:
    branches: 
      - master
    tags: '*'
  pull_request:
jobs:
  test:
    name: Code-coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: action/checkout@v4
      - name: Install requirements
        uses: pytest --cov --cov-branch --cov-resport=xml
      - name: Calculate Code Coverage
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN}}
